plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'by.slavik'
version = '0.0.1-SNAPSHOT'
description = 'book-catalog'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //log
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.13.0'

    // spring
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // PostgreSQL, JPA, migration
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    tasks.named('test') {
        useJUnitPlatform()
    }
}